### ISSUE TITLE
Move links menu kadavy to gallery.html in leonardo-module-links

### ISSUE THREAD

**Issue by michaelkuty** [dresl/leonardo-theme-kkadavy#1]
https://github.com/dresl/leonardo-theme-kkadavy/blob/master/leonardo_theme_kkadavy/templates/widget/linkmenu/kkadavy.html

to https://github.com/leonardo-modules/leonardo-module-links

**Comment by dresl** [comment]
Done.
https://github.com/leonardo-modules/leonardo-module-links/pull/4
